export const skills = [
  ['', 'HTML 5'],
  ['', 'CSS'],
  ['', 'Javascript'],
  ['ﯤ', 'Typescript'],
  ['', 'Sass'],
  ['', 'Less'],
  ['', 'Material UI'],
  ['', 'React'],
  ['', 'Angular'],
  ['', 'Nodejs'],
  ['', 'MongoDB'],
  ['', 'MySQL'],
  ['', 'PostgreSQL'],
  ['', 'Git'],
  ['', 'Github'],
  ['', 'Gitlab'],
  ['', 'Vim/NeoVim'],
  ['', 'VSCode'],
  ['', 'Jira'],
  ['', 'Trello']
];
